/* ============================================================
   蛋仔单词本 · 英语释义表（与课本《Adventures in Japanese 1》
   Lesson 3 的英文注释保持一致）
   用途：主释义显示英语（孩子的最强语言），中文作辅助参考
   ============================================================ */

window.SEED_EN = {

  /* ══════════ Part 1 · 我的家庭 ══════════ */
  "かぞく": "family",
  "きょうだい": "brothers and sisters; siblings",
  "なまえ": "name",
  "だれ": "who",

  /* ── 人数助数词 ── */
  "ひとり": "one person (irregular)",
  "ふたり": "two people (irregular)",
  "さんにん": "three people",
  "よにん": "four people (irregular)",
  "ごにん": "five people",
  "ろくにん": "six people",
  "ななにん": "seven people",
  "はちにん": "eight people",
  "きゅうにん": "nine people",
  "じゅうにん": "ten people",
  "じゅういちにん": "eleven people",
  "なんにん": "how many people",

  /* ── 年龄 ── */
  "いっさい": "one year old",
  "にさい": "two years old",
  "さんさい": "three years old",
  "よんさい": "four years old",
  "ごさい": "five years old",
  "ろくさい": "six years old",
  "ななさい": "seven years old",
  "はっさい": "eight years old (irregular)",
  "きゅうさい": "nine years old",
  "じゅっさい": "ten years old",
  "じゅういっさい": "eleven years old",
  "はたち": "twenty years old (irregular)",
  "なんさい": "how old",
  "おいくつ": "how old (polite)",

  /* ── 表达 & 补充词 ── */
  "そうですか": "I see.; Is that so?",
  "ほんとうですか": "Really?; Is it true?",
  "の": "of; 's (possessive particle)",
  "いぬ": "dog",
  "ねこ": "cat",
  "どなた": "who (polite)",
  "ペット": "pet",
  "ぎりの～": "the ... on one's behalf; the ... for someone",
  "うえの～": "the older ... (e.g., my older brother)",
  "したの～": "the younger ... (e.g., my younger brother)",
  "そふ": "grandfather (my own)",
  "そぼ": "grandmother (my own)",

  /* ══════════ Part 2 · 朋友的家庭（敬称） ══════════ */
  "おとうさん": "(someone else's) father",
  "おかあさん": "(someone else's) mother",
  "おじいさん": "grandfather",
  "おばあさん": "grandmother",
  "おにいさん": "(someone else's) older brother",
  "おねえさん": "(someone else's) older sister",
  "おとうとさん": "(someone else's) younger brother",
  "いもうとさん": "(someone else's) younger sister",
  "と": "and",
  "ごかぞく": "(someone else's) family (honorific)",
  "おなまえ": "(someone else's) name (honorific)",
  "そして": "and then; and also",
  "おじさん": "uncle",
  "おばさん": "aunt",
  "いとこ": "cousin",

  /* ══════════ Part 3 · 学校年级 ══════════ */
  "がっこう": "school",
  "せいと": "student (of one's own school)",
  "がくせい": "student",
  "ちゅうがく": "junior high school",
  "こうこう": "high school",
  "ちゅうがくせい": "junior high school student",
  "こうこうせい": "high school student",
  "ちゅうがくいちねんせい": "1st-year junior high student (7th grade)",
  "ちゅうがくにねんせい": "2nd-year junior high student (8th grade)",
  "ちゅうがくさんねんせい": "3rd-year junior high student (9th grade)",
  "こうこういちねんせい": "1st-year high school student (10th grade)",
  "こうこうにねんせい": "2nd-year high school student (11th grade)",
  "こうこうさんねんせい": "3rd-year high school student (12th grade)",
  "なんねんせい": "what school year (grade)",
  "～も": "as many as; also (emphasis)",
  "だいがく": "university; college",
  "だいがくせい": "university student",
  "しょうがっこう": "elementary school",
  "しょうがくせい": "elementary school student",
  "ようちえん": "kindergarten",
  "ほいくえん": "nursery school; daycare",

  /* ══════════ Part 4 · 国籍 ══════════ */
  "どこ": "where",
  "こちら": "this way; this person (polite)",
  "にほん": "Japan",
  "にほんじん": "Japanese (person)",
  "アメリカ": "America; the U.S.",
  "アメリカじん": "American (person)",
  "なにじん": "what nationality",
  "ちゅうごく": "China",
  "かんこく": "Korea",
  "フランス": "France",
  "スペイン": "Spain",
  "インド": "India",
  "ブラジル": "Brazil",
  "ロシア": "Russia",
  "イギリス": "the U.K.; Britain",
  "ドイツ": "Germany",
  "メキシコ": "Mexico",
  "フィリピン": "the Philippines",
  "ナイジェリア": "Nigeria",
  "にっけいじん": "person of Japanese descent",

  /* ══════════ Part 5 · 职业 ══════════ */
  "おしごと": "(someone's) job; occupation (polite)",
  "いしゃ": "doctor (physician)",
  "おいしゃさん": "(someone else's) doctor (polite)",
  "びょういん": "hospital",
  "べんごし": "lawyer",
  "かいしゃいん": "company employee",
  "しゅふ": "housewife; homemaker",
  "エンジニア": "engineer",
  "けいかん": "police officer",
  "しょうぼうし": "firefighter",
  "ウェイター": "waiter",
  "シェフ": "chef; cook",
  "まえ": "before; in front of",
  "こうむいん": "government worker; public servant",
  "かいけいし": "accountant",
  "ひしょ": "secretary",
  "パイロット": "pilot",
  "フライトアテンダント": "flight attendant",
  "ふどうさんや": "real estate agent",
  "しゃちょう": "company president",
  "かんごし": "nurse",
  "びようし": "hairdresser; beautician",
  "やくざいし": "pharmacist"
};
